name: Build monkey-jsonviewer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装依赖
        run: pnpm install

      - name: 构建
        run: pnpm run build
