name: Build monkey-jsonviewer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 安装依赖
        run: npm install

      - name: 构建
        run: npm run build
      - name: Commit and push dist
        run: |
          git config --global user.email "1220301855@qq.com"
          git config --global user.name "xFeny"
          git add dist
          git commit -m "Build and deploy"
          git push origin main